install:
  - git submodule update --init

build_script:
  - ps: .\build.ps1 -Target "CIntegration"

branches:
  only:
    - develop
    - main

cache:
  - src\packages -> src\packages.config, tests\packages.config
  - tools -> tools\packages.config
